pipeline
 {
  agent any
  stages{
   stage('Build Application') 
   {
   steps{
   bat 'mvn -f tc1/pom.xml clean install'
   }
   }
   stage('Deploy Application into cloud') 
   {
   steps{
   bat 'mvn package deploy -DmuleDeploy'
   }
   }
  }

 }